"""
TelNova Communications - Finance Analytics
Dashboard Data Export
=================================================
Reads the FINISHED, recalculated .xlsx workbook and embeds its contents
directly into dashboard/index.html as window.TELNOVA_FINANCE_DATA, plus
inlines the vendored Chart.js and SheetJS libraries. The result is a
single, fully self-contained HTML file with ZERO external network
dependencies -- it opens correctly with a plain double-click, on any
network, with no server.

An optional "Reload live from Excel" button in the dashboard re-parses
the .xlsx directly via SheetJS when the project is served over http/https.

Author: Milad Shabani
"""

import json
import re
import numpy as np
import pandas as pd
from datetime import datetime
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
VENDOR_DIR = os.path.join(SCRIPT_DIR, "vendor")

WORKBOOK_PATH = os.path.join(PROJECT_ROOT, "data", "Finance_Analytics_Workbook.xlsx")
DASHBOARD_HTML_PATH = os.path.join(PROJECT_ROOT, "dashboard", "index.html")
OUT_PATH = os.path.join(PROJECT_ROOT, "dashboard", "data.js")  # reference export, not required by the dashboard

HEADER_ROW_0INDEXED = {
    "Revenue_EBITDA_Forecast": 4, "Cashflow_Forecast": 4, "Capex_Plan": 4, "Budget_Risk": 4,
}


def read_sheet(sheet_name):
    header = HEADER_ROW_0INDEXED.get(sheet_name, 0)
    df = pd.read_excel(WORKBOOK_PATH, sheet_name=sheet_name, header=header, engine="openpyxl")
    df = df.dropna(how="all")
    return df


def to_records(df):
    df = df.copy()
    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            df[col] = df[col].dt.strftime("%Y-%m-%d")
    df = df.replace({np.nan: None})
    return df.to_dict(orient="records")


def main():
    print("Reading workbook sheets...")
    revenue = read_sheet("Revenue_By_Segment")
    pnl = read_sheet("PnL")
    balance = read_sheet("Balance_Sheet")
    cashflow = read_sheet("Cash_Flow")
    capex = read_sheet("Capex_Projects")
    debt = read_sheet("Debt_Schedule")
    budget = read_sheet("Budget_vs_Actual")
    cust_econ = read_sheet("Customer_Economics")
    revenue_fc = read_sheet("Revenue_EBITDA_Forecast")
    cashflow_fc = read_sheet("Cashflow_Forecast")
    capex_fc = read_sheet("Capex_Plan")
    budget_risk = read_sheet("Budget_Risk")

    # Recompute formula-derived P&L/BS columns independently from raw numbers,
    # so the export is correct even without a LibreOffice recalculation pass.
    # (PnL/Balance Sheet here are already values, not formulas, so no
    # recompute needed -- unlike the HR project's CompaRatio column.)

    # ---- Pre-aggregate capex: by month x category (dashboard charts by category) ----
    capex_by_mc = (capex.groupby(["Month", "Category", "CapexType"], as_index=False)
                   .agg(PlannedBudgetUSD=("PlannedBudgetUSD", "sum"),
                        ActualSpendUSD=("ActualSpendUSD", "sum")))

    data = {
        "Revenue": to_records(revenue),
        "PnL": to_records(pnl),
        "Balance": to_records(balance),
        "CashFlow": to_records(cashflow),
        "CapexByMonthCategory": to_records(capex_by_mc),
        "Debt": to_records(debt),
        "Budget": to_records(budget),
        "CustomerEcon": to_records(cust_econ),
        "RevenueForecast": to_records(revenue_fc),
        "CashflowForecast": to_records(cashflow_fc),
        "CapexPlan": to_records(capex_fc),
        "BudgetRisk": to_records(budget_risk),
        "_meta": {
            "generatedAt": datetime.now().isoformat(timespec="seconds"),
            "sourceWorkbook": "Finance_Analytics_Workbook.xlsx",
            "totalSubscribers": 1_047_500,
        },
    }

    for k, v in data.items():
        if isinstance(v, list):
            print(f"  {k:20s} -> {len(v)} records")

    js_content = (
        "// AUTO-GENERATED by scripts/export_dashboard_data.py -- do not edit by hand.\n"
        "// Build-time snapshot of Finance_Analytics_Workbook.xlsx so the dashboard works\n"
        "// offline with a plain double-click (no local server required).\n"
        "// Regenerate with: python scripts/build_all.py\n"
        "window.TELNOVA_FINANCE_DATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
    )
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(js_content)
    size_kb = len(js_content.encode("utf-8")) / 1024
    print(f"\nWrote {OUT_PATH} ({size_kb:.0f} KB) [reference export, not required by the dashboard]")

    # ---- Embed data + vendor libs directly into dashboard/index.html ----
    with open(DASHBOARD_HTML_PATH, "r", encoding="utf-8") as f:
        html = f.read()

    inline_data_script = (
        '<script id="telnova-embedded-data">\n'
        "window.TELNOVA_FINANCE_DATA = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n"
        "</script>"
    )
    pattern = re.compile(r'<script id="telnova-embedded-data">.*?</script>', re.S)
    if not pattern.search(html):
        raise RuntimeError('Could not find the <script id="telnova-embedded-data"> placeholder in dashboard/index.html.')
    html = pattern.sub(lambda m: inline_data_script, html, count=1)

    def inline_vendor(html_text, placeholder_id, vendor_filename):
        vendor_path = os.path.join(VENDOR_DIR, vendor_filename)
        with open(vendor_path, "r", encoding="utf-8") as vf:
            lib_code = vf.read()
        pat = re.compile(r'<script id="' + re.escape(placeholder_id) + r'">.*?</script>', re.S)
        if not pat.search(html_text):
            raise RuntimeError(f'Could not find placeholder <script id="{placeholder_id}"> in dashboard/index.html.')
        replacement = f'<script id="{placeholder_id}">\n{lib_code}\n</script>'
        return pat.sub(lambda m: replacement, html_text, count=1)

    html = inline_vendor(html, "vendor-chartjs", "chart.umd.js")
    html = inline_vendor(html, "vendor-xlsx", "xlsx.full.min.js")

    with open(DASHBOARD_HTML_PATH, "w", encoding="utf-8") as f:
        f.write(html)

    html_size_kb = len(html.encode("utf-8")) / 1024
    print(f"Embedded dataset + Chart.js + SheetJS directly into {DASHBOARD_HTML_PATH} ({html_size_kb/1024:.2f} MB total)")
    print("This file now has ZERO external network dependencies -- it works fully offline.")


if __name__ == "__main__":
    main()
